-- ==========================================================================
-- Sri Products — Business Manager migration onto Supabase (Phase 5,
-- foundation). Run in the SQL Editor AFTER schema.sql, 002_delivery.sql,
-- 003_online_payment.sql. This file only lays the groundwork — tables,
-- locking/ID primitives, and staff-auth helpers — that the rest of the
-- migration (004b, 004c, ... in this same staff/ folder) builds on.
--
-- Design, so the "why" survives past this session:
--
-- 1. Staff auth uses real Supabase Auth (email/password, real bcrypt
--    hashing, real JWT sessions) instead of the Sheets version's
--    hand-rolled SHA-256 + a Sessions sheet nobody ever pruned. A
--    `staff_profiles` row (keyed by the Supabase auth user's id) is
--    how "which role is this person" and "are they still active" are
--    tracked — mirrors Code.gs's Users sheet, minus the password
--    column (Supabase Auth owns that entirely now).
--
-- 2. Every table in this migration has RLS enabled with **no policies
--    granted to anyone** — all reads and writes go through
--    SECURITY DEFINER functions that call require_staff()/require_admin()
--    themselves, exactly mirroring Code.gs's requireSession()/
--    requireAdmin() calls at the top of nearly every function. There is
--    deliberately no "authenticated users can just SELECT the sales
--    table" policy — that would make the per-function authorization
--    checks in 005/006/007 pointless, since raw table access would
--    bypass them entirely.
--
-- 3. Human-readable IDs (SALE-000123, QT-000045, etc.) are kept as a
--    unique text column generated by next_id(), same prefixes/padding
--    as Code.gs, alongside a uuid primary key used for foreign keys.
--    This is deliberate: app.js builds URLs like #/sales/SALE-000123
--    and displays these IDs throughout — keeping them means api.js can
--    stay a thin shim instead of needing to translate IDs everywhere.
--
-- 4. next_id() uses an INSERT ... ON CONFLICT DO UPDATE ... RETURNING,
--    which is atomic on its own in Postgres — no equivalent of Code.gs's
--    explicit LockService.getScriptLock() is needed here.
-- ==========================================================================

-- ---------- STAFF AUTH ----------

create table if not exists staff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null check (role in ('Admin', 'Staff')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table staff_profiles enable row level security;
-- No policies granted here on purpose (see note 2 above). Staff read
-- their own profile via the get_current_user RPC in 004b, not by
-- selecting this table directly.

-- Returns the calling user's staff row, or raises if they're not a
-- recognized/active staff member — mirrors Code.gs's requireSession().
create or replace function require_staff() returns staff_profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff staff_profiles;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated.';
  end if;
  select * into v_staff from staff_profiles where id = auth.uid() and active;
  if v_staff is null then
    raise exception 'User is not active or not recognized as staff.';
  end if;
  return v_staff;
end;
$$;

-- Mirrors Code.gs's requireAdmin(). Call after require_staff() (or use
-- this alone — it calls require_staff() itself) in any function that
-- should be Admin-only.
create or replace function require_admin() returns staff_profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff staff_profiles;
begin
  v_staff := require_staff();
  if v_staff.role <> 'Admin' then
    raise exception 'This action requires Admin access.';
  end if;
  return v_staff;
end;
$$;

-- Used by api.js right after login to get { userId, name, role } the
-- same shape Code.gs's login()/requireSession() returned.
create or replace function get_current_staff() returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff staff_profiles;
begin
  v_staff := require_staff();
  return jsonb_build_object('userId', v_staff.id, 'name', v_staff.name, 'role', v_staff.role);
end;
$$;

grant execute on function get_current_staff() to authenticated;

-- ---------- ID / COUNTER PRIMITIVES ----------

create table if not exists counters (
  prefix text primary key,
  next_number bigint not null default 0
);

create or replace function next_id(p_prefix text, p_pad_length int) returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_next bigint;
begin
  insert into counters (prefix, next_number) values (p_prefix, 1)
    on conflict (prefix) do update set next_number = counters.next_number + 1
    returning next_number into v_next;
  return p_prefix || lpad(v_next::text, p_pad_length, '0');
end;
$$;

-- ---------- SETTINGS ----------
-- Separate from the storefront's store_settings (different concerns —
-- companyName/gstEnabled/prefixes here vs. delivery_fee there).

create table if not exists app_settings (
  key text primary key,
  value text not null
);

insert into app_settings (key, value) values
  ('companyName', 'Sri Products'),
  ('motto', 'Quality never compromised'),
  ('gstEnabled', 'false'),
  ('saleNumberPrefix', 'SALE-'),
  ('quotationNumberPrefix', 'QT-'),
  ('paymentNumberPrefix', 'PAY-'),
  ('customerNumberPrefix', 'CUS-'),
  ('logoUrl', '')
on conflict (key) do nothing;

create or replace function get_settings() returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb) from app_settings;
$$;

create or replace function update_settings(p_updates jsonb) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text;
begin
  perform require_admin();
  for v_key in select jsonb_object_keys(p_updates) loop
    insert into app_settings (key, value) values (v_key, p_updates->>v_key)
      on conflict (key) do update set value = p_updates->>v_key;
  end loop;
  return get_settings();
end;
$$;

grant execute on function get_settings() to authenticated;
grant execute on function update_settings(jsonb) to authenticated;

-- ---------- CUSTOMERS ----------
-- New table — the storefront currently only has guest checkout
-- (orders.customer_name/customer_phone, no customers table), so this
-- is the first real Customers table in Supabase. Storefront accounts
-- (Phase 4, B2B) will link to this table once built.

create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  legacy_customer_id text,           -- e.g. 'CUS-00012', if imported from Sheets
  customer_id text not null unique,  -- human-readable id, e.g. 'CUS-00012' going forward too
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by text,
  last_modified_at timestamptz not null default now(),
  last_modified_by text
);

alter table customers enable row level security;

-- ---------- ITEMS: add the column Code.gs's Items sheet has that the
-- storefront's items table doesn't yet ----------

alter table items add column if not exists tax_rate numeric(5,2) not null default 0;

-- ---------- BOTTLE ADJUSTMENTS ----------

create table if not exists bottle_adjustments (
  id uuid primary key default gen_random_uuid(),
  adjustment_id text not null unique,
  item_id uuid not null references items(id) on delete cascade,
  effective_from date not null,
  amount numeric(10,2) not null,
  created_by text,
  created_at timestamptz not null default now(),
  unique (item_id, effective_from)
);

alter table bottle_adjustments enable row level security;

-- ---------- STOCK: ledger + balance primitives ----------
-- stock_balances already exists (created for the storefront:
-- item_id, balance, reserved, updated_at). Business Manager
-- operations (sales, production, manual adjustments) adjust `balance`
-- directly, same column the storefront's v_catalog reads as
-- `balance - reserved` — this is the single shared source of truth
-- for "how much stock exists" that both the storefront and the
-- Business Manager read/write from now on.

create table if not exists stock_movements (
  id uuid primary key default gen_random_uuid(),
  movement_id text not null unique,
  occurred_at timestamptz not null default now(),
  item_id uuid not null references items(id),
  quantity numeric(10,2) not null,     -- signed: negative = stock out, positive = stock in
  unit text not null,
  movement_type text not null,         -- 'Sale', 'SaleEdit', 'SaleVoid', 'Production', 'ProductionEdit', 'ProductionDelete', 'StockAdjustment'
  reference_type text,
  reference_id text,
  notes text,
  created_by text,
  created_at timestamptz not null default now()
);

alter table stock_movements enable row level security;

-- Upsert is atomic on its own — no LockService equivalent needed.
create or replace function adjust_stock_balance(p_item_id uuid, p_delta numeric) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into stock_balances (item_id, balance, reserved, updated_at)
    values (p_item_id, p_delta, 0, now())
  on conflict (item_id) do update set balance = stock_balances.balance + p_delta, updated_at = now();
end;
$$;

-- Core primitive every domain (sales, production, adjustments) calls
-- instead of touching stock_movements/stock_balances directly —
-- mirrors Code.gs's recordStockMovement().
create or replace function record_stock_movement(
  p_item_id uuid,
  p_quantity numeric,
  p_unit text,
  p_movement_type text,
  p_reference_type text,
  p_reference_id text,
  p_notes text,
  p_created_by text
) returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_movement_id text;
begin
  v_movement_id := next_id('MOV', 6);
  insert into stock_movements (movement_id, item_id, quantity, unit, movement_type, reference_type, reference_id, notes, created_by)
  values (v_movement_id, p_item_id, p_quantity, p_unit, p_movement_type, p_reference_type, p_reference_id, coalesce(p_notes, ''), p_created_by);
  perform adjust_stock_balance(p_item_id, p_quantity);
  return v_movement_id;
end;
$$;

-- ---------- PLACEHOLDER TABLES FOR SALES / QUOTATIONS / PRODUCTION ----------
-- Table DDL lives here (not in the per-domain function files) so the
-- functions written for each domain never have to agree on schema
-- with each other — they're all handed an already-fixed shape.

create table if not exists sales (
  id uuid primary key default gen_random_uuid(),
  sale_id text not null unique,
  sale_date date not null,
  customer_id uuid not null references customers(id),
  subtotal numeric(10,2) not null default 0,
  tax_amount numeric(10,2) not null default 0,
  grand_total numeric(10,2) not null default 0,
  amount_received numeric(10,2) not null default 0,
  outstanding numeric(10,2) not null default 0,
  gst_enabled boolean not null default false,
  quotation_ref text,
  status text not null default 'Active' check (status in ('Active', 'Voided')),
  void_reason text,
  created_by text,
  created_at timestamptz not null default now(),
  last_modified_by text,
  last_modified_at timestamptz not null default now()
);

create table if not exists sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_item_id text not null unique,
  sale_id text not null references sales(sale_id) on delete cascade,
  item_id uuid not null references items(id),
  quantity numeric(10,2) not null,
  unit text not null,
  base_rate numeric(10,2) not null,
  bottle_adjustment numeric(10,2) not null default 0,
  final_rate numeric(10,2) not null,
  amount numeric(10,2) not null,
  tax_rate numeric(5,2) not null default 0,
  tax_amount numeric(10,2) not null default 0
);

create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  payment_id text not null unique,
  customer_id uuid not null references customers(id),
  sale_id text references sales(sale_id),
  amount numeric(10,2) not null,
  payment_date date not null,
  method text,
  notes text,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists quotations (
  id uuid primary key default gen_random_uuid(),
  quotation_id text not null unique,
  quotation_date date not null,
  customer_id uuid not null references customers(id),
  subtotal numeric(10,2) not null default 0,
  tax_amount numeric(10,2) not null default 0,
  grand_total numeric(10,2) not null default 0,
  valid_until date,
  status text not null default 'Draft' check (status in ('Draft', 'Sent', 'Accepted', 'Converted', 'Expired')),
  created_by text,
  created_at timestamptz not null default now(),
  last_modified_by text,
  last_modified_at timestamptz not null default now()
);

create table if not exists quotation_items (
  id uuid primary key default gen_random_uuid(),
  quotation_item_id text not null unique,
  quotation_id text not null references quotations(quotation_id) on delete cascade,
  item_id uuid not null references items(id),
  quantity numeric(10,2) not null,
  unit text not null,
  base_rate numeric(10,2) not null,
  bottle_adjustment numeric(10,2) not null default 0,
  final_rate numeric(10,2) not null,
  amount numeric(10,2) not null,
  tax_rate numeric(5,2) not null default 0,
  tax_amount numeric(10,2) not null default 0
);

create table if not exists production (
  id uuid primary key default gen_random_uuid(),
  production_id text not null unique,
  occurred_on date not null,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  last_modified_by text,
  last_modified_at timestamptz not null default now()
);

create table if not exists production_inputs (
  id uuid primary key default gen_random_uuid(),
  production_input_id text not null unique,
  production_id text not null references production(production_id) on delete cascade,
  item_id uuid not null references items(id),
  quantity_consumed numeric(10,2) not null
);

create table if not exists production_outputs (
  id uuid primary key default gen_random_uuid(),
  production_output_id text not null unique,
  production_id text not null references production(production_id) on delete cascade,
  item_id uuid not null references items(id),
  quantity_produced numeric(10,2) not null
);

alter table sales enable row level security;
alter table sale_items enable row level security;
alter table payments enable row level security;
alter table quotations enable row level security;
alter table quotation_items enable row level security;
alter table production enable row level security;
alter table production_inputs enable row level security;
alter table production_outputs enable row level security;

-- No RLS policies on any of the tables in this file, and no grants to
-- `authenticated` on the tables themselves — every read/write goes
-- through the SECURITY DEFINER functions in this file and the
-- following 004b/005/006/007 migrations, each of which calls
-- require_staff()/require_admin() itself.
